apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - externalsecret.yaml

configMapGenerator:
  - name: linkr-config
    literals:
      - LINKR_ENV=production
      - LINKR_LOG_LEVEL=INFO
      - LINKR_BASE_URL=https://linkr.example.com

images:
  - name: ghcr.io/CedricCloudOps/linkr
    newTag: latest
