apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkr
spec:
  tls:
    - hosts:
        - lnkr.dev
      secretName: linkr-tls
  rules:
    - host: lnkr.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkr
                port:
                  number: 80
